### DISCUSSION TITLE
Kubernetes - Run RavenDB as non root

### DISCUSSION THREAD

**Discussion by mario-zelger** [ravendb/ravendb#14483] [Ideas]
If I'm not mistaken, RavenDB inside a Docker Container / Kubernetes Pod is running with the root user. Have you guys considered running it with a non-root user? This would have the benefit to further lock down the Pod for example with a security context similarily to something like this:

```yaml
 securityContext:
    runAsNonRoot: true
    runAsUser: 10000
    runAsGroup: 10000
    [...]
```
