### DISCUSSION TITLE
How to get Raven to use these env vars from docker compose?

### DISCUSSION THREAD

**Discussion by damccull** [ravendb/ravendb#14967] [General]
Hi. I'm trying to use docker compose to set up a 3 instance development cluster on my local PC with the following environment variables:
```yml
    environment:
      - "RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork"
      - "RAVEN_Setup_Mode=None"
      - "RAVEN_License_Eula_Accepted=true"
      - "RAVEN_ServerUrl=http://0.0.0.0:8080"
      - "RAVEN_PublicServerUrl=http://hostos:8080"
      - "RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:38888"
      - "RAVEN_PublicServerUrl_Tcp=tcp://hostos:38888"
```
I'm still getting an error on the web studio, however.
![image](https://user-images.githubusercontent.com/401104/190950384-ab41d9fd-91e7-47f3-b3c1-91c2b0746311.png)

How do I solve this?

**Comment by ayende** [comment]
At a glance, this looks correct.
Maybe you need to lose the quotes there? Not sure on the phrasing.
If you bash into the instance, do you see those values properly?

**Reply by ppekrol** [reply]
@damccull Have you tried taking (and modifying for your needs) our sample script: https://github.com/ravendb/ravendb/blob/v5.4/docker/compose/linux-cluster/docker-compose.yml ?

**Reply by damccull** [reply]
I tried almost the exact file you linked. My problem was the `- RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork` from what I can tell. I was unable to get raven to recognize that variable, so I had to use `- "RAVEN_ARGS=--Security.UnsecuredAccessAllowed=PublicNetwork"` to get it working. It DID, however recognize `- "RAVEN_Setup_Mode=None"`. So I have a backward experience from you.

I found the following docker-compose and bash script at https://www.davidboike.dev/2019/06/creating-a-ravendb-cluster-in-docker/

Using this docker-compose:
```yml
version: '3.9'

x-raven-template:
  &raven-template
  image: ravendb/ravendb:ubuntu-latest
  extra_hosts:
    - "mycomputer:10.0.0.2"
  environment:
    - "RAVEN_Security_UnsecuredAccessAllowed='PublicNetwork'"
    - "RAVEN_Setup_Mode=None"
    - "RAVEN_License_Eula_Accepted=true"
    - "RAVEN_ServerUrl=http://0.0.0.0:8080"
    - "RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:38888"
    - "RAVEN_ARGS=--Security.UnsecuredAccessAllowed=PublicNetwork"

services:
  raven1:
    <<: *raven-template
    container_name: raven1
    ports:
      - 8080:8080
      - 38888:38888
    environment:
      - "RAVEN_PublicServerUrl=http://mycomputer:8080"
      - "RAVEN_PublicServerUrl_Tcp=tcp://mycomputer:38888"
      - "RAVEN_Security_UnsecuredAccessAllowed='PublicNetwork'"
      - "RAVEN_Setup_Mode=None"
      - "RAVEN_License_Eula_Accepted=true"
      - "RAVEN_ServerUrl=http://0.0.0.0:8080"
      - "RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:38888"
      - "RAVEN_ARGS=--Security.UnsecuredAccessAllowed=PublicNetwork"
  raven2:
    <<: *raven-template
    container_name: raven2
    ports:
      - 8081:8080
      - 38889:38888
    environment:
      - "RAVEN_PublicServerUrl=http://mycomputer:8081"
      - "RAVEN_PublicServerUrl_Tcp=tcp://mycomputer:38889"
      - "RAVEN_Security_UnsecuredAccessAllowed='PublicNetwork'"
      - "RAVEN_Setup_Mode=None"
      - "RAVEN_License_Eula_Accepted=true"
      - "RAVEN_ServerUrl=http://0.0.0.0:8080"
      - "RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:38888"
      - "RAVEN_ARGS=--Security.UnsecuredAccessAllowed=PublicNetwork"
  raven3:
    <<: *raven-template
    container_name: raven3
    ports:
      - 8082:8080
      - 38890:38888
    environment:
      - "RAVEN_PublicServerUrl=http://mycomputer:8082"
      - "RAVEN_PublicServerUrl_Tcp=tcp://mycomputer:38890"
      - "RAVEN_Security_UnsecuredAccessAllowed='PublicNetwork'"
      - "RAVEN_Setup_Mode=None"
      - "RAVEN_License_Eula_Accepted=true"
      - "RAVEN_ServerUrl=http://0.0.0.0:8080"
      - "RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:38888"
      - "RAVEN_ARGS=--Security.UnsecuredAccessAllowed=PublicNetwork"

networks:
  backend:
```

With this bash script to setup:
```bash
#!/bin/bash

LICENSE_JSON="{my minified json license}"

echo "Running docker-compose up"
docker-compose -f docker_compose.yml up --detach

sleep 2

echo "Applying license..."
curl 'http://localhost:8080/admin/license/activate' -H 'Content-Type: application/json; charset=UTF-8' --data-binary "$LICENSE_JSON" --compressed ;

echo "Assigning 1 core for leader node..."
curl 'http://localhost:8080/admin/license/set-limit?nodeTag=A&newAssignedCores=1' -X POST -H 'Content-Type: application/json; charset=utf-8' -H 'Content-Length: 0' --compressed ;

echo "Adding raven2 to the cluster..."
curl 'http://localhost:8080/admin/cluster/node?url=http%3A%2F%2Fmycomputer%3A8081&watcher=true&assignedCores=1' -X PUT -H 'Content-Type: application/json; charset=utf-8' -H 'Content-Length: 0' --compressed

echo "Adding raven3 to the cluster..."
curl 'http://localhost:8080/admin/cluster/node?url=http%3A%2F%2Fmycomputer%3A8082&watcher=true&assignedCores=1' -X PUT -H 'Content-Type: application/json; charset=utf-8' -H 'Content-Length: 0' --compressed
```
