### DISCUSSION TITLE
Ingress/certificate settings for RavenDb cluster in kubernetes

### DISCUSSION THREAD

**Discussion by jamesbramich** [ravendb/ravendb#15436] [General]
Hi, I have been asked to set up a RavenDb cluster in Kubernetes as we're looking to move a lot of data from SQL server to RavenDb so apologies in advance - I'm pretty new to RavenDb.

I have been looking at the instructions here: https://ravendb.net/docs/article-page/5.4/csharp/start/installation/setup-examples/kubernetes/azure-aks

My understanding of having a 'cluster' would be that clients communicate with the 'cluster' and the cluster implementation (or kubernetes load balancer) would distribute requests to RavenDb server nodes.

The sample configuration has a headless service plus ingress to each individual RavenDb server configured. Is this necessary? I found an example with a single service for the loadbalancer [here ](https://github.com/ravendb/ravendb/discussions/14760) but the stateful set in question only has a single replica so I'm not sure it would scale.

I guess to summarise:

- Would  a loadblancer pointed to the headless service work/be a supported configuration?
- I also have an existing cert-manager/let's encrypt wildcard certificate (*.internal.company.com) in my cluster which is replicated between namespaces as a kubernetes.ie/tls secret, can this be used as the server certificate? Is it as simple as putting the secret name where the SSL volume is specified in the stateful set?

Many thanks,

James

**Comment by garayx** [comment]
Hi

The recommended way to run RavenDB is cluster so you will have availability & redundancy. Since the data in RavenDB cluster is consistent, the server will still process writes & requests as long as a single cluster node is available (see [cluster-overview docs atricle](https://ravendb.net/docs/article-page/5.4/csharp/server/clustering/overview#cluster-overview)). 
Cluster let you distribute the work (such as [database tasks](https://ravendb.net/docs/article-page/5.4/csharp/studio/database/tasks/ongoing-tasks/general-info)) and read requests for better performance ([load balance](https://ravendb.net/docs/article-page/5.4/csharp/client-api/configuration/load-balance-and-failover#conventions-load-balance--failover)) among the cluster nodes.

RavenDB support self signed certificates (see: https://ravendb.net/docs/article-page/5.4/csharp/server/security/authentication/certificate-configuration#standard-manual-setup-with-certificate-stored-locally) but we recommend to use [Let's Encrypt](https://ravendb.net/docs/article-page/5.4/csharp/server/security/authentication/lets-encrypt-certificates) certificates so RavenDB will manage the renewals of cetrificates.

**Comment by ayende** [comment]
In addition to that, you need ingress for each individual server, yes. And you need to setup SSL Passthrough.

**Reply by jamesbramich** [reply]
Thank you, I have the cert-manager certificate sorted out and definitely intend to use a cluster.

I would just like to clarify what traffic needs to flow from outside the cluster directly to indidual ravendb node servers. If a client is requesting an individual server that has crashed, how does failover work?

Creating a serivce for each pod seems contrary to the idea of a kubernetes service in the first place.

**Reply by garayx** [reply]
the failover is managed by the RavenDB Client, see; https://ravendb.net/docs/article-page/5.4/Csharp/client-api/cluster/how-client-integrates-with-replication-and-cluster#configuring-topology-nodes on 1st connect it fetches the server topology, so in case one of the nodes is down it will try to connect to the other one.

**Reply by jamesbramich** [reply]
Thanks for that Egor.

I am thinking of testing a loadbalancer like the following and using the (same) load balancer IP for each of the node hostnames:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: ravendb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"   # only expose to AKS vnet
  labels:
    app: ravendb
spec:
  ports:
  - name: http-api
    port: 443
    protocol: TCP
    targetPort: 443
  - name: tcp-server
    port: 38888
    protocol: TCP
    targetPort: 38888
  - name: snmp
    port: 161
    protocol: TCP
    targetPort: 161
  selector:
    app: ravendb
  type: LoadBalancer
---
```
This will mean all client requests are passed to an active node, although possibly not the one the client requested. Do you know of fhand if that would cause problems? I am happy to test this if it is an unknown.

I am not trying to be overly difficult. I just think that a configuration that didn't require new services to be created if we wanted to scale up the cluster.
