### DISCUSSION TITLE
How to store client certificate in Kubernetes

### DISCUSSION THREAD

**Discussion by JoshClose** [ravendb/ravendb#16410] [Q&A] [answered]
What is the best way to store the client certificate that my application uses to connect to RavenDB Cloud? I'm new to Kubernetes and not sure of the best way to do this.

**Comment by JoshClose** [comment, marked as answer]
I figured this out.

Create a secret for the RavenDB certificate file.

```
$ kubectl create secret generic ravendb-certificate --from-file my.client.certificate.pfx
```

Then in the deployment you can mount the secret as a volume and use that.

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: registry/my-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: RavenDB__CertFilePath
              value: secrets/my.client.certificate.pfx
          volumeMounts:
            - name: secrets
              mountPath: /app/secrets
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: ravendb-certificate
```
