### DISCUSSION TITLE
Docker containers - Can't connect through Java client or on the RavenDB Studio

### DISCUSSION THREAD

**Discussion by Honeyxilia** [ravendb/ravendb#18583] [Q&A] [answered]
hello everyone :)

for a project where we have to try and use locally a NoSQL database, i have tried to setup several containers corresponding to several nodes of a cluster with a docker-compose file : 

```yml
services:
  raven_node_1:
    container_name: raven_node_1
    image: ravendb/ravendb:ubuntu-latest
    ports:
      - "8060:8080"
      - "33000:33000"
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_Logs_Mode=Information
      - RAVEN_ARGS=--Setup.Mode=None
      - RAVEN_ServerUrl=http://localhost:8060
      - RAVEN_PublicServerUrl=http://localhost:8060
      - RAVEN_ServerUrl_Tcp=tcp://localhost:33000
      - RAVEN_License_Eula_Accepted=true
    env_file:
      - ./ravendb_licence.env

  raven_node_2:
    container_name: raven_node_2
    image: ravendb/ravendb:ubuntu-latest
    ports:
      - "8061:8080"
      - "33001:33000"
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_ARGS=--Setup.Mode=None
      - RAVEN_ServerUrl=http://localhost:8060
      - RAVEN_PublicServerUrl=http://localhost:8061
      - RAVEN_ServerUrl_Tcp=tcp://localhost:33001
      - RAVEN_License_Eula_Accepted=true
    env_file:
      - ./ravendb_licence.env

  raven_node_3:
    container_name: raven_node_3
    image: ravendb/ravendb:ubuntu-latest
    ports:
      - "8062:8080"
      - "33002:33000"
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_ARGS=--Setup.Mode=None
      - RAVEN_ServerUrl=http://localhost:8060
      - RAVEN_PublicServerUrl=http://localhost:8062
      - RAVEN_ServerUrl_Tcp=tcp://localhost:33002
      - RAVEN_License_Eula_Accepted=true
    env_file:
      - ./ravendb_licence.env
 ```

after starting these containers with `docker-compose up` the terminal displays that they are in server mode - i then try to access them with a Java client, by creating an IDocumentStore : 
```java
this.databaseURLs = new String[] {
                                 new String[]{
						"http://localhost:8060", // Node A
						"http://localhost:8061", // Node B
						"http://localhost:8062", // Node C
				}
}

IDocumentStore store = new DocumentStore(
				this.databaseURLs,
				"databaseName"
		);
		store.initialize();
		return store;
```

However, after using the store to store an object `store.openSession().store()`, I get this exception  : 

```
Tried to send net.ravendb.client.documents.identity.HiLoResult request via GET http://localhost:8062/databases/databaseName/hilo/next?tag=users&lastBatchSize=0&identityPartsSeparator=%2F&lastMax=0 to all configured nodes in the topology, none of the attempt succeeded.
Topology: 
[Url: http://localhost:8060, ClusterTag: !, ServerRole: null, Exception: An exception occurred while contacting http://localhost:8060/databases/databaseName/hilo/next?tag=users&lastBatchSize=0&identityPartsSeparator=%2F&lastMax=0.
java.net.SocketException: Connection reset
The server at http://localhost:8060/databases/databaseName/hilo/next?tag=users&lastBatchSize=0&identityPartsSeparator=%2F&lastMax=0 responded with status code: 503]
[Url: http://localhost:8061, ClusterTag: !, ServerRole: null, Exception: An exception occurred while contacting http://localhost:8061/databases/MovieRenting/hilo/next?tag=users&lastBatchSize=0&identityPartsSeparator=%2F&lastMax=0.
org.apache.hc.core5.http.NoHttpResponseException: localhost:8061 failed to respond
The server at http://localhost:8061/databases/databaseName/hilo/next?tag=users&lastBatchSize=0&identityPartsSeparator=%2F&lastMax=0 responded with status code: 503]
[Url: http://localhost:8062, ClusterTag: !, ServerRole: null, Exception: An exception occurred while contacting http://localhost:8062/databases/MovieRenting/hilo/next?tag=users&lastBatchSize=0&identityPartsSeparator=%2F&lastMax=0.
java.net.SocketException: Connection reset
The server at http://localhost:8062/databases/databaseName/hilo/next?tag=users&lastBatchSize=0&identityPartsSeparator=%2F&lastMax=0 responded with status code: 503]
```

also, when I try to get on the web client RavenDB Studio, I get hit with a `NS_NET_ERROR_RESET` error...

is there a step to the initialization i forgot ? it seems that i followed all the steps of the documentation - also, i'm using RavenDB 6.0

can you help me ? ty in advance!

**Comment by ayende** [comment]
The issue is here:

```
    ports:
      - "8060:8080"
```

`8060:8080`: This notation means that the container’s port 8080 is mapped to the host machine’s port 8060.

However, lower you have:

```
      - RAVEN_ServerUrl=http://localhost:8060
      - RAVEN_PublicServerUrl=http://localhost:8060
      - RAVEN_ServerUrl_Tcp=tcp://localhost:33000
```

So you are binding to port 8060 _in the container_, but exposing port 8080 _in the container_ to port 8060 in the host.

Note that you also have typo errors with 8060 and 8061 at the same time, which is not valid

I think that this should be sufficient for you (just one node to test):
```
services:
  raven_node_1:
    container_name: raven_node_1
    image: ravendb/ravendb:ubuntu-latest
    ports:
      - "8080:8060"
      - "33000:33000"
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_Logs_Mode=Information
      - RAVEN_ARGS=--Setup.Mode=None
      - RAVEN_ServerUrl=http://localhost:8080
      - RAVEN_PublicServerUrl=http://localhost:8080
      - RAVEN_ServerUrl_Tcp=tcp://localhost:33000
      - RAVEN_License_Eula_Accepted=true
    env_file:
      - ./ravendb_licence.env
```

Note that after you spawn those nodes, you still need to generate a cluster from them by telling them about each other

**Reply by Honeyxilia** [reply]
ty for the answer!
unfortunally, by doing this with only, i just obtain a RavenException provoked by a HttpHostConnectException when trying to connect to it with the Java client (only on `http://localhost:8060` ) :(
and i cant access to the RavenDB Studio interface either...

As for the clustering, I will think of doing that in the java client initialization process!

**Reply by ayende** [reply]
Start from the basics, are you able to run this at all?
When you are running the docker command directly, are you able to access the Studio?

**Reply by Honeyxilia** [reply]
i am able to run the setup i had posted as well as the once you posted - here's the return of the terminal once i run the docker-compose
``` [ Logo and system info]
raven_node_1  | Using GC in server concurrent mode.
raven_node_1  | Node A in cluster b4ecd6d8-f822-48ac-b4b2-d0d9256d7441
raven_node_1  | Server available on: http://localhost:8080
raven_node_1  | Tcp listening on [::1]:33000, 127.0.0.1:33000
raven_node_1  | Server started, listening to requests...
raven_node_1  | TIP: type 'help' to list the available commands.
raven_node_1  | ravendb> End of standard input detected, switching to server mode...
raven_node_1  | Running non-interactive.
```

when i run this command in the terminal : 
`docker run --rm -d -p 8080:8080 -p 33000:33000 -v /var/lib/ravendb/data --name raven_test1 -e RAVEN_Setup_Mode=None -e RAVEN_License_Eula_Accepted=true -e RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork ravendb/ravendb`

it does work and i'm able to access the Studio !

i experimented some more, and it seems that the following environnement variables : 
```    
- RAVEN_ServerUrl=http://localhost:8060
      - RAVEN_PublicServerUrl=http://localhost:8060
      - RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:33000
 ```

make it so that it doesnt forward the connection outside of the docker correctly... i removed them and now i can access the studio app !
i will check if adding other services with the same env. variables, but with different forwarded addresses will make it work c:

ty for your assistance !!

**Reply by ayende** [reply]
Once you are done, would love it if you could post the whole thing here.

**Reply by Honeyxilia** [reply, marked as answer]
I went and found the way to set internal IPs, with a `networks` section in the docker-compose file, as well as applying an IP address for each of the nodes : 

```yml
  raven_node_1:
    container_name: raven_node_1
    image: ravendb/ravendb
    ports:
      - "8080:8080"
      - "38888:38888"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_Logs_Mode=Information
      - RAVEN_ARGS=--Setup.Mode=None
      - RAVEN_License_Eula_Accepted=true
      - "RAVEN_ServerUrl=http://172.29.1.1:8080"
      - "RAVEN_ServerUrl_Tcp=tcp://172.29.1.1:38888"
    env_file:
      - ./ravendb_licence.env
    networks:
      raven_network:
        ipv4_address: 172.29.1.1

  raven_node_2:
    container_name: raven_node_2
    image: ravendb/ravendb
    ports:
      - "8081:8081"
      - "38889:38889"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_Logs_Mode=Information
      - RAVEN_ARGS=--Setup.Mode=None
      - RAVEN_License_Eula_Accepted=true
      - "RAVEN_ServerUrl=http://172.29.1.2:8081"
      - "RAVEN_ServerUrl_Tcp=tcp://172.29.1.2:38888"
    networks:
      raven_network:
        ipv4_address: 172.29.1.2

  raven_node_3:
    container_name: raven_node_3
    image: ravendb/ravendb
    ports:
      - "8082:8082"
      - "38890:38890"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_Logs_Mode=Information
      - RAVEN_ARGS=--Setup.Mode=None
      - RAVEN_License_Eula_Accepted=true
      - "RAVEN_ServerUrl=http://172.29.1.3:8082"
      - "RAVEN_ServerUrl_Tcp=tcp://172.29.1.3:38888"
    networks:
      raven_network:
        ipv4_address: 172.29.1.3

networks:
  raven_network:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
 ```
source : https://github.com/Particular/NServiceBus.RavenDB/blob/03505d396e75578847d4cdf6b4a144d2e5698965/docker-compose.yml

However, while i can access each individual server through the Studio and the Java client through the `localhost:<PORT>` address, they need the internal public addresses to connect to each other

To be able to automate the connection and clustering, i'm currently inputing each address in my code, but i want to be able to retrieve it in the code - is there an API endpoint to obtain a server info such as `PublicServerUrl` ? I tried to find but there's no seeming endpoint in the documentation :(

*EDIT* : I just noticed that the `/cluster/topology` endpoint gives the `PublicServerUrl` as `WebUrl` - ty for your assistance for the main issue!
