### DISCUSSION TITLE
AggressivelyCache hangs ASP.NET requests when RavenDB is in Windows Docker container

### DISCUSSION THREAD

**Discussion by kamranayub** [ravendb/ravendb#19178] [Q&A] [answered]
Yes, I know 😃 I have a .NET Framework 4.7.2 app that I'm dockerizing. I originally had been running RavenDB 6.0.105 locally on my machine, and now I have it running successfully in a Windows Docker container.

I also have my app successfully running in a IIS docker container.

However, when I debug it, I noticed something strange: regular queries/loads work fine, but calling `session.Advanced.AggressivelyCache()` hangs the ASP.NET thread.

It feels like this: https://github.com/ravendb/ravendb/issues/16981

Now, I _think_ I may know the problem but I'm not exactly sure and it has to do with the Docker setup.

Here is my compose file (adjusted slightly for public sharing):

```yml
services:

  db:
    image: ravendb/ravendb:6.0-windows-ltsc2022-latest
    hostname: app-db
    container_name: app-db
    ports:
      - "8080:8080"
      - "38888:38888"
    environment:
      - "RAVEN_PublicServerUrl=https://app-db:8080"
      - "RAVEN_PublicServerUrl_Tcp=tcp://app-db:38888"
      - "RAVEN_Setup_Mode=None"
      - "RAVEN_License_Eula_Accepted=true"
      - "RAVEN_Security_Certificate_LetsEncrypt_Email=myemail"
      - "RAVEN_Security_Certificate_Path=C:\\RavenDB\\Config\\cluster.server.certificate.db.pfx"
      - "RAVEN_ServerUrl=https://0.0.0.0:8080"
      - "RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:38888"
      - "RAVEN_ARGS=--ServerUrl=https://0.0.0.0:8080 --Setup.Mode=None"
    volumes:
      - E:\RavenDB\Server\RavenData:C:\RavenDB\Server\RavenData
      - E:\RavenDB\Server\Config:C:\RavenDB\Config

  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: src\Web
      dockerfile: Dockerfile
    volumes:
      - E:\RavenDB\Local:c:\certs
    depends_on:
      - db
```

(Using VS 2022 Docker Compose support)

As you can see, I've got two services, my website and the DB server. I'm using 8080 defaults. I'm _currently_ using my previous cluster admin certificate from when I initially created my local RavenDB server. This was created initially using a `*.ravendb.community` `PublicServerUrl` and I'd access it using that hostname.

I _suspect_ this is the issue; that I need to re-issue my admin certificate under this container `app-db` host. I can still successfully connect to RavenDB Studio using my client certificate (issued by the `ravendb.community` host), and the cert is working insofar as it can connect and load documents from the ASP.NET container.

The code I can see it hanging on is this (line 1):

```c#
using (session.Advanced.DocumentStore.AggressivelyCache())
{
    return session.Advanced.Lazily.LoadStartingWith<Doc>(
        "Doc/", pageSize: 1024);
}
```

Where `session` is `IDocumentStore`.

- RavenDB Client: 6.0.105
- RavenDB Server: 6.0.105

And this was working when I wasn't using Docker.

If you have any ideas, let me know otherwise I'll keep trying some things, like re-issuing a new certificate. I could maybe also just _not_ use auth locally? But it's so close! 😄
