### DISCUSSION TITLE
Pod Fails to Start - Back-off restarting failed container ravendb

### DISCUSSION THREAD

**Discussion by tzarger** [ravendb/ravendb#19257] [General]
Hello, I am trying to get RavenDB to run in Kubernetes. When it pulls the image, it starts the image and immediately fails and goes into a constant CrashLoopBackOff. Here is the output when describing the pod:

```
+ kubectl describe pods ravendb-0
Name:             ravendb-0
Namespace:        default
Priority:         0
Service Account:  default
Node:             ravendb-nodes-0eef791af44e/10.5.112.8
Start Time:       Thu, 12 Sep 2024 17:22:47 -0400
Labels:           app=ravendb
                  apps.kubernetes.io/pod-index=0
                  controller-revision-hash=ravendb-6d67c5455f
                  statefulset.kubernetes.io/pod-name=ravendb-0
Annotations:      cni.projectcalico.org/containerID: 16b4e9c3973b04e4e58e9705ead150a044c0c45c55b02dfeb241c01ecfdd9810
                  cni.projectcalico.org/podIP: 10.244.166.74/32
                  cni.projectcalico.org/podIPs: 10.244.166.74/32,fd10:1ba:6d2c:1000:2797:bff7:a3c5:59ca/128
Status:           Running
IP:               10.244.166.74
IPs:
  IP:           10.244.166.74
  IP:           fd10:1ba:6d2c:1000:2797:bff7:a3c5:59ca
Controlled By:  StatefulSet/ravendb
Containers:
  ravendb:
    Container ID:  containerd://5796d0247c59a3f6502b438c6e8901696ed1ca2c020915a2e3d1642b0782ee52
    Image:         ravendb/ravendb:ubuntu-latest
    Image ID:      docker.io/ravendb/ravendb@sha256:929669d90d87783dd2f57d8f9a8942917c07abed832930679bd2ba255c99bd7d
    Ports:         443/TCP, 38888/TCP, 161/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/sh
      -c
      /opt/RavenDB/Server/Raven.Server --config-path /config/$HOSTNAME
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    127
      Started:      Thu, 12 Sep 2024 17:24:33 -0400
      Finished:     Thu, 12 Sep 2024 17:24:33 -0400
    Ready:          False
    Restart Count:  4
    Environment:    <none>
    Mounts:
      /config from config (rw)
      /data from data (rw)
      /license from license (rw)
      /ssl from ssl (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-r9j6c (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-ravendb-0
    ReadOnly:   false
  ssl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ravendb-ssl
    Optional:    false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      ravendb-settings
    Optional:  false
  license:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ravendb-license
    Optional:    false
  kube-api-access-r9j6c:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                   From                     Message
  ----     ------                  ----                  ----                     -------
  Normal   Scheduled               3m11s                 default-scheduler        Successfully assigned default/ravendb-0 to ravendb-nodes-0eef791af44e
  Normal   SuccessfulAttachVolume  3m7s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-1bf4d77c80964e35"
  Normal   Pulled                  3m4s                  kubelet                  Successfully pulled image "ravendb/ravendb:ubuntu-latest" in 587ms (587ms including waiting). Image size: 310638266 bytes.
  Normal   Pulled                  3m3s                  kubelet                  Successfully pulled image "ravendb/ravendb:ubuntu-latest" in 585ms (585ms including waiting). Image size: 310638266 bytes.
  Normal   Pulled                  2m46s                 kubelet                  Successfully pulled image "ravendb/ravendb:ubuntu-latest" in 564ms (564ms including waiting). Image size: 310638266 bytes.
  Normal   Created                 2m16s (x4 over 3m4s)  kubelet                  Created container ravendb
  Normal   Started                 2m16s (x4 over 3m4s)  kubelet                  Started container ravendb
  Normal   Pulled                  2m16s                 kubelet                  Successfully pulled image "ravendb/ravendb:ubuntu-latest" in 588ms (588ms including waiting). Image size: 310638266 bytes.
  Warning  BackOff                 99s (x8 over 3m1s)    kubelet                  Back-off restarting failed container ravendb in pod ravendb-0_default(2410f9e4-ce6a-4b7a-89a5-0e2333add5a3)
```

Unfortunely, I have no idea what the error is since there is no output and the pod never gets spun up due to the CrashLoopBackOff.

How would you go about fixing this?

Thank you,
Troy

**Comment by tzarger** [comment]
Found this in the logs finally:

```
+ kubectl logs -f ravendb-0
/bin/sh: 1: /opt/RavenDB/Server/Raven.Server: not found
```

**Comment by mario-zelger** [comment]
I'm not from the RavenDB team but we use Raven extensively in a Kubernetes environment. I see that you override the `command` directly to pass in the `--config-path` argument. I'd advise against that as Raven is executing a custom startup script to get the container going (see [here](https://github.com/ravendb/ravendb/blob/e142267eec0a2e87ad342d533d1ff0d49a5412e6/docker/ravendb-ubuntu/Dockerfile.x64#L40C1-L40C61)).

As per the [documentation](https://ravendb.net/docs/article-page/6.0/csharp/start/installation/running-in-docker-container#q-how-can-i-pass-command-line-arguments) you should use the `RAVEN_ARGS` environment variable to pass arguments to Raven. In your case it would be `RAVEN_ARGS="--config-path /config/$HOSTNAME"`. Not sure if `$HOSTNAME` is going to be recognized correcly in that scenario though.

You can see how the argument are being passed to the command [here](https://github.com/ravendb/ravendb/blob/e142267eec0a2e87ad342d533d1ff0d49a5412e6/docker/ravendb-ubuntu/run-raven.sh#L32).
```bash
if [ ! -z "$RAVEN_ARGS" ]; then
	COMMAND="$COMMAND ${RAVEN_ARGS}"
fi
```

**Reply by tzarger** [reply]
Hi @mario-zelger thank you for your response. That command came from RavenDB Documentation... altough the YAML files are a bit outdated, so I had to redo a fair amount to get it to work. I had permission issues, fix using ports under 1024 for a non-root user, then set permissions for the use inside the docker for RavenDB which in my case was running a user with 999 ... Lots of changes it seems the K8S I am using has some differences with the examples in the documentation. Perhaps I overkilled it, but if you have any YAML files you might be willing to share, you could send them directly, that would be great. The setup I have running has 3 nodes in the cluster.

**Reply by mario-zelger** [reply]
You're right. The linked YAML from the documentation is not really made for v6. I guess it was a good starting point for v5. 

We created a custom Helm Chart that I can't share directly to deploy our RavenDB instances. Here's a reduced example of an applied configuration. Keep in mind that we still use v5. For v6 you'd have to adjust the mount path of the data directory and one could further enhance the `securityContext` to set `runAsNonRoot` to `true` for example. Port wise everything should work with v6 as well because we're not using a reserved port.

For certificate management we use [cert-manager](https://cert-manager.io/). The attached volumes related to certificates use the secrets that are generated via cert-manager.

You'll also see that we mainly use environment variables to configure the RavenDB settings.

**Service**
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: my-ravendb
  name: my-ravendb
  namespace: my-namespace
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: my-ravendb
  ports:
  - name: http-api
    port: 8443
    protocol: TCP
  - name: tcp-server
    port: 38888
    protocol: TCP
```

**StatefulSet**
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-ravendb
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: my-ravendb
  serviceName: my-ravendb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-ravendb
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
          # In our experience it is helpful to configure the time zone if you don't want to rely on UTC.
          # e.g. the backup cron schedule follows the configured time zone
        - name: TZ
          value: <your-timezone>
        - name: RAVEN_Setup_Mode
          value: "None"
        - name: RAVEN_License_Eula_Accepted
          value: "true"
        - name: RAVEN_ServerUrl
          value: "https://0.0.0.0:8443"
        - name: RAVEN_ServerUrl_Tcp
          value: "tcp://0.0.0.0:38888"
        - name: RAVEN_PublicServerUrl
          value: "https://my-ravendb.my-namespace.svc.cluster.local:8443"
        - name: RAVEN_PublicServerUrl_Tcp
          value: "tcp://my-ravendb.my-namespace.svc.cluster.local:38888"
        - name: RAVEN_Security_UnsecuredAccessAllowed
          value: "None"
        - name: RAVEN_License_Path
          value: "/license.json"
        - name: RAVEN_Security_Certificate_Path
          value: "/usr/local/cluster-certificate.p12"
        - name: RAVEN_Security_Certificate_Password
          valueFrom:
            secretKeyRef:
              key: certificatePassword
              name: my-ravendb-cluster-tls-password
        image: "ravendb/ravendb:5.4.201-ubuntu.22.04-x64"
        imagePullPolicy: "Always"
        name: "ravendb"
        ports:
        - containerPort: 8443
          name: http-api
          protocol: TCP
        - containerPort: 38888
          name: tcp-server
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /opt/RavenDB/healthcheck.sh
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 4Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          privileged: false
        volumeMounts:
        - mountPath: /opt/RavenDB/Server/RavenData
          name: ravendb-data
        - mountPath: /license
          name: license
          readOnly: true
        - mountPath: /usr/local/cluster-certificate.p12
          name: cluster-certificate
          readOnly: true
          subPath: keystore.p12
        - mountPath: /etc/ssl/certs/cluster-ca.crt
          name: cluster-certificate
          readOnly: true
          subPath: ca.crt
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 120
      volumes:
      - name: license
        secret:
          defaultMode: 420
          secretName: ravendb-license
      - name: cluster-certificate
        secret:
          defaultMode: 420
          secretName: my-ravendb-cluster-tls
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ravendb-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: <your-storage-requirement>
      storageClassName: <your-storage-class>
```

Hope this helps!

**Reply by mario-zelger** [reply]
Additionally, here's the basic configuration for our cluster certificate created by cert-manager.

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: my-ravendb
  name: my-ravendb-cluster
  namespace: my-namespace
# For more details see https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateSpec
spec:
  dnsNames:
  - my-ravendb.my-namespace.svc.cluster.local
  # If you want to access the instance web UI from outside the cluster
  - my-ravendb.contoso.local
  duration: <your-duration>
  renewBefore: <your-renew-before-time>
  issuerRef:
    kind: ClusterIssuer
    name: my-internal-ca-issuer
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: certificatePassword
        name: my-ravendb-cluster-tls-password
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    rotationPolicy: Always
    size: 4096
  secretName: my-ravendb-cluster-tls
  secretTemplate:
    labels:
      app.kubernetes.io/name: my-ravendb
  # Add your subject config here
  subject: {}
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
```
