### DISCUSSION TITLE
Full access to raven studio without certificate

### DISCUSSION THREAD

**Discussion by heiner-suter** [ravendb/ravendb#19518] [Q&A]
We run RavenDB in a secured environment behind a proxy that does not support forwarding the certificate. User access is controlled by the proxy.

We can access Raven Studio but only with restricted access.
We tried to set UnsecuredAccessAllowed to PublicNetwork. But it did not help.

How can we access Raven Studio with full privileges from a remote machine without using certificates for authentication?

**Comment by ayende** [comment]
That goes pretty much directly against the security principles in RavenDB.
When you are using secured RavenDB, you _must_ provide a certificate for auth.

Note that you can use something like `stunnel` for this, something like:


```
stunnel -c -d 127.0.0.1:12345 -r remote.server.com:54321 \
    -p client-cert.pem \
    -k client-key.pem \
    -A ca-cert.pem \
    -V "verify=3" \
    -W "checkHost=remote.server.com"
```

That should allow you to connect to the `127.0.0.1:12345` address, which will proxy + client cert auth for you.



```
-c: Enables client mode.

-d 127.0.0.1:12345: Specifies the local address and port to listen on.

-r remote.server.com:54321: Specifies the remote server address and port to connect to.

-p client-cert.pem: Specifies the client certificate file.

-k client-key.pem: Specifies the client private key file.

-A ca-cert.pem: Specifies the CA certificate file for verifying the server certificate.

-V "verify=3": Enables verification of the server's certificate chain.

-W "checkHost=remote.server.com": Specifies the hostname to check against the server's certificate.

Replace the placeholders with your actual values. This should get you set up.
```

**Reply by heiner-suter** [reply]
Thanks for your answer. But we have no option to change the proxy in our environment.
We need to run RavenDB unsecure, as we cannot use certificates. But we need to access Raven Studio. Is there a way?

**Reply by krivulcik** [reply]
Not sure if I understand your needs correctly, but if you need to only access the studio using the proxy server, then the following might work:
 - Configure RavenDB to be completely unsecured.
 - Allow access only from the proxy.
 - As you mentioned, the proxy controls the user access.

This setup wouldn't protect the database from the hostile network, but since no access would be allowed except from the trusted proxy, it might be reasonably secure and meet your needs.

**Reply by heiner-suter** [reply]
Thanks @krivulcik 

I don't see the difference. 
Raven Studio is in read-only mode. Probably because it is not accessed from localhost.
How can I access Raven Studio with all rights from another host without certificates?

**Reply by krivulcik** [reply]
When the server is configured as unsecured, it should allow all access without any authentication/authorization:

https://ravendb.net/docs/article-page/6.2/csharp/start/installation/setup-wizard#select-setup-mode

The live-test instance is configured without security, and everyone has full access without any auth:

http://live-test.ravendb.net/studio/index.html

**Reply by ayende** [reply]
@heiner-suter That is the case, yes. I think that you defined RavenDB _with_ security, even though you have `PublicAccess` 

Can you share the `settings.json` (redact any sensitive details, of course)

**Reply by heiner-suter** [reply]
We run it on Kubernetes. With RAVEN_Setup_Mode=None. 
So it could be that there is another setting missing.
Currently, when connecting to Raven Studio, it is in read-only mode.
On my local machine, when I connect from localhost, it works just fine.

**Reply by heiner-suter** [reply]
Thanks for your help @ayende 

I cannot find settings.json on the server. Only settings.default.json. 
We are providing the settings as environment variables:
```
          env:
            - name: RAVEN_Logs_Mode
              value: operations
            - name: RAVEN_ARGS
              value: --log-to-console
            - name: RAVEN_License_Eula_Accepted
              value: "true"
            - name: RAVEN_Setup_Mode
              value: None
            - name: RAVEN_DataDir
              value: /var/lib/ravendb/data
            - name: RAVEN_ServerUrl
              value: http://0.0.0.0:{{ .Values.service.port }}
```
