### DISCUSSION TITLE
Can't get telemetry to be emitted via OTLP

### DISCUSSION THREAD

**Discussion by andreasohlund** [ravendb/ravendb#20142] [Q&A] [answered]
I'm running a collector on my machine and hosting raven in a docker container with these settings doesn't emit telemetry, tried both gRPC and HttpProtobuf. Other containers in the same compose file are emitting fine, nothing is seen in the logs.

```
 environment:
      RAVEN_Monitoring_OpenTelemetry_Enabled: true
      RAVEN_Monitoring_OpenTelemetry_OpenTelemetryProtocol_Enabled: true
      RAVEN_Monitoring_OpenTelemetry_OpenTelemetryProtocol_Protocol: HttpProtobuf
      RAVEN_Monitoring_OpenTelemetry_Meters_Server_Storage_Enabled: true
      RAVEN_Monitoring_OpenTelemetry_Meters_Server_Resources_Enabled: true
      RAVEN_Monitoring_OpenTelemetry_OpenTelemetryProtocol_Endpoint: http://host.docker.internal:4318/v1/metrics
```

Settings show up fine in Raven Studio

![image](https://github.com/user-attachments/assets/fb5845e9-b90c-4cdb-acb7-d185b47b0057)

Any ideas on how to troubleshoot this further?
