### DISCUSSION TITLE
INTEGRATION ANNOUNCEMENT: Ansible Galaxy Collection

### DISCUSSION THREAD

**Discussion by ppekrol** [ravendb/ravendb#20840] [Announcements]
To help you automate RavenDB instances and operations, we’re introducing the RavenDB Ansible Collection. It’s a **repeatable** way to operate RavenDB at scale, letting you easily cover common deployment scenarios in your playbooks. It helps to manage instances, databases, indexes, and certificates by providing a precise way to define multi-node RavenDB clusters.

### 🚀 Key Features
- Automatic cluster discovery, database & index automation
- Built-in secrets, license, and certificates management.
- No manual steps - less time spent configuring, more time **building**

And more! Check our [article](https://ravendb.net/articles/full-lifecycle-automation-of-ravendb-with-ansible) to dig deeper.

### 🧪 Sample Usage

```yaml
- name: Multimap Index
  hosts: ravendb_nodes
  gather_facts: no

  roles:
    - ravendb.ravendb.ravendb_python_client_prerequisites
  tasks:
    - name: Ensure RavenDB Index is present
      ravendb.ravendb.index:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        index_name: "UsersAndOrdersByName"
        index_definition:
          map:
            - "from c in docs.Users select new { Name = c.name, UserCount = 1, OrderCount = 0, TotalCount = 1 }"
            - "from o in docs.Orders select new { Name = o.customer, UserCount = 0, OrderCount = 1, TotalCount = 1 }"
          reduce: >
            from result in results
            group result by result.Name
            into g
            select new 
            { 
              Name = g.Key, 
              UserCount = g.Sum(x => x.UserCount),
              OrderCount = g.Sum(x => x.OrderCount),
              TotalCount = g.Sum(x => x.TotalCount)
            }
        state: present
```

### 📚 Learn More

Don’t hesitate to contact us for **feature requests**; we’ll see if we can put it on our roadmap.
- 📘 [README](https://github.com/ravendb/ansible-collection-ravendb) — requirements, configuration examples, and usage details

- 🐛 [Issues](https://github.com/ravendb/ansible-collection-ravendb/issues) — found a bug? Let us know!

- 👾 [Discord](https://discord.com/invite/ravendb)— join our Discord community, chat with our core team, and join our online events.
