### ISSUE TITLE
Request: RavenDb support K8s cert-manager

### ISSUE THREAD

**Issue by JohnGalt1717** [ravendb/ravendb#14437]
One of the things that we've always struggled with is getting certificate stuff right especially in K8s.

It would be nice to extend support for K8s cert-manager issued certificates and provide an example. Cert-manager can generate Let's encrypt certificates and stores them in secrets which you can then mount in your deployment/statefulset like this:
```
         containers:
             ...
              volumeMounts:
                 - mountPath: "/certificates/internal"
                   name: "internal"
         volumes:
            - name: internal
              secret:
                 secretName: internal-tls

```

The result of this is a tls.key, tls.crt and tls.ca (if you're using an internally self-signed CA.)

Ideally we would be able to use the cert-manager acme system to create an issuer that generates an internal certificate that has the Let's encrypt CA as the root CA for the certificate issued.

We would then mount the secret that this creates as a volume in the statefulset for RavenDb and then point RavenDb to the path for the tls.crt and tls.key. (there is no way to automate this to create the pfx that is currently required)

By doing this, we could have automatic certificates in the cluster that were trusted and could be verified throughout and not have to manually generate containers for the CA (which isn't possible with cert-manager because of renews and key rotations that would be unpredictable and would have to be regenerated manually)

This would be a major win for usability and security in k8s.
