### ISSUE TITLE
Dockerized RavenDB ports setups

### ISSUE THREAD

**Issue by adambajguz** [ravendb/ravendb#18052]
Hi RavenDB Team,
I was trying to setup an unsecured RavenDB instance on custom ports and I had some difficulties I'd like to share. After many attempts I've managed to run the instance (see `raven-1` container). However, I don't understand why other configurations don't work (three example attempts are in the docker-compose.yml below).

I'm not sure if it's a bug or not, but is seems like setting the `ServerUrl` makes the database inaccessible (or maybe there are some reasons while these configurations don't work). Also it seems that inside the container RavenDB must run on ports 8080 and 38888 - at least I wasn't able to make it work on other ports.

Anyway it would also be great to have more examples of how to setup the dockerized database (https://ravendb.net/docs/article-page/6.0/csharp/server/configuration/core-configuration and https://ravendb.net/docs/article-page/6.0/csharp/start/installation/running-in-docker-container) e.g. with custom ports, addresses, and certificate.

### docker-compose.yml
```yml
version: "3.8"
name: raven-test
services:
  ### raven-1
  # Working database:
  raven-1:
    container_name: ravendb-1
    image: ravendb/ravendb:latest
    ports:
      - 58000:8080
      - 58001:38888
    environment:
      RAVEN_Setup_Mode: 'Unsecured'
      RAVEN_RunInMemory: 'true'
      RAVEN_License_Eula_Accepted: 'true'
      RAVEN_Security_UnsecuredAccessAllowed: 'PrivateNetwork'
      RAVEN_ServerUrl_Tcp: '38888'
      RAVEN_PublicServerUrl: 'http://localhost:8080'
      RAVEN_PublicServerUrl_Tcp: 'tcp://localhost:58001'

  ### raven-2
  # 'Running in a potentially unsafe mode' error on page http://localhost:58002/
  raven-2:
    container_name: ravendb-2
    image: ravendb/ravendb:latest
    ports:
      - 58002:58002
      - 58003:58003
    environment:
      RAVEN_Setup_Mode: 'Unsecured'
      RAVEN_RunInMemory: 'true'
      RAVEN_License_Eula_Accepted: 'true'
      RAVEN_Security_UnsecuredAccessAllowed: 'PrivateNetwork'
      RAVEN_ServerUrl: 'http://0.0.0.0:58002'
      RAVEN_ServerUrl_Tcp: '58003'
      RAVEN_PublicServerUrl: 'http://localhost:58002'
      RAVEN_PublicServerUrl_Tcp: 'tcp://localhost:58003'

  ### raven-3
  # Studio opens with http://localhost:58004/studio/index.html but and exception is raised after creating a database
  #   System.IO.InvalidDataException: The database 'ss' was created but is not accessible, because all of the nodes on which this database was supposed to reside on, threw an exception.
  #  ---> System.AggregateException: One or more errors occurred. (An exception occurred while contacting http://localhost:58004/rachis/waitfor?index=3.
  # System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:58004)
  #  ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
  #    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
  #    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
  #    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
  #    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
  #    --- End of inner exception stack trace ---
  #    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
  #    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
  #    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
  #    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
  #    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
  #    at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
  #    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
  #    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
  #    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
  #    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
  #    at Raven.Client.Http.RequestExecutor.SendAsync[TResult](ServerNode chosenNode, RavenCommand`1 command, SessionInfo sessionInfo, HttpRequestMessage request, CancellationToken token) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Client\Http\RequestExecutor.cs:line 1207
  #    at Raven.Client.Http.RequestExecutor.SendRequestToServer[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, HttpRequestMessage request, String url, CancellationToken token) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Client\Http\RequestExecutor.cs:line 1151.
  # The server at http://localhost:58004/rachis/waitfor?index=3 responded with status code: ServiceUnavailable.)
  #  ---> Raven.Client.Exceptions.RavenException: An exception occurred while contacting http://localhost:58004/rachis/waitfor?index=3.
  # System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:58004)
  #  ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
  #    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
  #    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
  #    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
  #    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
  #    --- End of inner exception stack trace ---
  #    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
  #    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
  #    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
  #    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
  #    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
  #    at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
  #    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
  #    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
  #    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
  #    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
  #    at Raven.Client.Http.RequestExecutor.SendAsync[TResult](ServerNode chosenNode, RavenCommand`1 command, SessionInfo sessionInfo, HttpRequestMessage request, CancellationToken token) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Client\Http\RequestExecutor.cs:line 1207
  #    at Raven.Client.Http.RequestExecutor.SendRequestToServer[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, HttpRequestMessage request, String url, CancellationToken token) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Client\Http\RequestExecutor.cs:line 1151.
  # The server at http://localhost:58004/rachis/waitfor?index=3 responded with status code: ServiceUnavailable.
  #  ---> System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:58004)
  #  ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
  #    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
  #    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
  #    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
  #    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
  #    --- End of inner exception stack trace ---
  #    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
  #    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
  #    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
  #    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
  #    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
  #    at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
  #    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
  #    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
  #    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
  #    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
  #    at Raven.Client.Http.RequestExecutor.SendAsync[TResult](ServerNode chosenNode, RavenCommand`1 command, SessionInfo sessionInfo, HttpRequestMessage request, CancellationToken token) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Client\Http\RequestExecutor.cs:line 1207
  #    at Raven.Client.Http.RequestExecutor.SendRequestToServer[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, HttpRequestMessage request, String url, CancellationToken token) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Client\Http\RequestExecutor.cs:line 1151
  #    --- End of inner exception stack trace ---
  #    at Raven.Client.Http.RequestExecutor.ThrowFailedToContactAllNodes[TResult](RavenCommand`1 command, HttpRequestMessage request) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Client\Http\RequestExecutor.cs:line 1319
  #    at Raven.Client.Http.RequestExecutor.SendRequestToServer[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, HttpRequestMessage request, String url, CancellationToken token)
  #    at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Client\Http\RequestExecutor.cs:line 1005
  #    at Raven.Client.Http.RequestExecutor.UnlikelyExecuteAsync[TResult](RavenCommand`1 command, JsonOperationContext context, Task topologyUpdate, SessionInfo sessionInfo, CancellationToken token) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Client\Http\RequestExecutor.cs:line 679
  #    at Raven.Server.Web.RequestHandler.<>c__DisplayClass27_0.<<WaitForExecutionOnRelevantNodes>g__ExecuteTask|0>d.MoveNext() in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Web\RequestHandler.cs:line 292
  #    --- End of inner exception stack trace ---
  #    --- End of inner exception stack trace ---
  #    at Raven.Server.Web.RequestHandler.WaitForExecutionOnRelevantNodes(JsonOperationContext context, String database, ClusterTopology clusterTopology, List`1 members, Int64 index) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Web\RequestHandler.cs:line 276
  #    at Raven.Server.Web.System.AdminDatabasesHandler.CreateDatabase(String name, DatabaseRecord databaseRecord, ClusterOperationContext context, Int32 replicationFactor, Nullable`1 index, String raftRequestId) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Web\System\AdminDatabasesHandler.cs:line 421
  #    at Raven.Server.Web.System.AdminDatabasesHandler.Put() in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Web\System\AdminDatabasesHandler.cs:line 284
  #    at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Routing\RequestRouter.cs:line 387
  #    at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\RavenServerStartup.cs:line 254
  raven-3:
    container_name: ravendb-3
    image: ravendb/ravendb:latest
    ports:
      - 58004:8080
      - 58005:38888
    environment:
      RAVEN_Setup_Mode: 'Unsecured'
      RAVEN_RunInMemory: 'true'
      RAVEN_License_Eula_Accepted: 'true'
      RAVEN_Security_UnsecuredAccessAllowed: 'PublicNetwork'
      RAVEN_ServerUrl_Tcp: '38888'
      RAVEN_PublicServerUrl: 'http://localhost:58004'
      RAVEN_PublicServerUrl_Tcp: 'tcp://localhost:58005'

  ### raven-4
  raven-4:
    container_name: ravendb-4
    image: ravendb/ravendb:latest
    ports:
      - 58006:8080
      - 58007:38888
    environment:
      RAVEN_Setup_Mode: 'Unsecured'
      RAVEN_RunInMemory: 'true'
      RAVEN_License_Eula_Accepted: 'true'
      RAVEN_Security_UnsecuredAccessAllowed: 'PrivateNetwork'
      RAVEN_ServerUrl: 'http://localhost:8080' # adding the ServerUrl (only difference from raven-1) breaks the setup - Studio not accessible with http://localhost:58006/
      RAVEN_ServerUrl_Tcp: '38888'
      RAVEN_PublicServerUrl: 'http://localhost:8080'
      RAVEN_PublicServerUrl_Tcp: 'tcp://localhost:58001'
```

**Comment by ml054** [comment]
Can you verify if machines can connect to each other + to itself (both tcp and http ports)?

**Comment by adambajguz** [comment]
It was running on local machine and I was accessing raven instances from the host. Do you mean check if e.g. raven-1 can connect to raven-4 (those instances are not a part of the cluster)?

**Comment by ml054** [comment]
Exactly:
local: from raven-1 to raven-1 and between raven-4 and raven-1 (both ways)

**Comment by adambajguz** [comment]
I don't know how there's no ping command inside the containers so I can't even ping them.

**Comment by adambajguz** [comment]
One more observation: 
raven-1 is not working properly as well. It works from studio but when I try to connect from C# client it tries to use http://localhost:8080 which is defined in PublicServerUrl (logical I think). So ultimately I have no idea how to get raven to work on custom ports.

I spent two days already and it's a bit frustring that a simple task of changing two ports is so challenging :(

**Comment by ml054** [comment]
Can you setup "ServerUrl" property as well?

RAVEN_PublicServerUrl: 'http://localhost:58004'
means: use localhost:58004 for lookback connection, but it doesn't bind to this port. 

Setting: 
ServerUrl should tell Raven on which port to listen.

**Comment by adambajguz** [comment]
```
```

**Comment by adambajguz** [comment]
With RAVEN_ServerUrl: 'http://0.0.0.0:58008' I receive 
<img width="549" alt="image" src="https://github.com/ravendb/ravendb/assets/23001378/1ab74b59-6b5b-4b1c-b9ca-8ce3dd1e6cc3">

With RAVEN_ServerUrl: 'http://localhost:58008' I can't access Studio from the browser on the host

```
 raven-5:
    container_name: ravendb-5
    image: ravendb/ravendb:latest
    ports:
      - 58008:58008
      - 58009:58009
    environment:
      RAVEN_Setup_Mode: 'Unsecured'
      RAVEN_RunInMemory: 'true'
      RAVEN_License_Eula_Accepted: 'true'
      RAVEN_Security_UnsecuredAccessAllowed: 'PrivateNetwork'
      RAVEN_ServerUrl: 'http://0.0.0.0:58008'
      RAVEN_ServerUrl_Tcp: '58009'
      RAVEN_PublicServerUrl: 'http://localhost:58008'
      RAVEN_PublicServerUrl_Tcp: 'tcp://localhost:58009'
```

**Comment by ml054** [comment]
What if you change: RAVEN_Security_UnsecuredAccessAllowed: 'PrivateNetwork' to RAVEN_Security_UnsecuredAccessAllowed: 'PublicNetwork'.

Also here is related documentation article: https://ravendb.net/docs/article-page/6.0/csharp/start/installation/running-in-docker-container

**Comment by adambajguz** [comment]
It looks I've overcomplicated the configuration because this one works:

```
  raven-5:
    container_name: ravendb-5
    image: ravendb/ravendb:latest
    ports:
      - 58008:8080
      - 58009:38888
    environment:
      RAVEN_Setup_Mode: 'Unsecured'
      RAVEN_RunInMemory: 'true'
      RAVEN_License_Eula_Accepted: 'true'
      RAVEN_Security_UnsecuredAccessAllowed: 'PrivateNetwork'
```

However, I still don't know if it's possible to change containers internal ports (8080, 38888) and what if I want to access raven with an URL other than localhost. I wish there are more real life examples in the docs.
