### ISSUE TITLE
.net Aspire Host Definition?

### ISSUE THREAD

**Issue by JohnGalt1717** [ravendb/ravendb#18706]
Is there a Aspire library for RavenDb yet?

Any guidance on doing so if not?

**Comment by ayende** [comment]
Hi,
I'm afraid that there isn't any yet.
We would be happy to assist in creating one, though.

At a glance, it is basically just setting things up to use the docker instance, no?

**Comment by JohnGalt1717** [comment]
In general it's doing 2 things:

1. Setting up a resource that can be depended upon by other resources and that means abstracting away connection strings, etc.
2. Setting up a definition that generates metadata (yaml) that can be converted into cloud services like Azure, AWS, Google Cloud and Kubernetes on any platform.

So there's a couple of facets here:

1. The easy part is generating a definition for the resource that works in development to spin up the right container.  This also means things like setting the environment variables, and configuration location etc.
2. Abstracting a connection string is more difficult because RavenDb doesn't use classic connection strings (to my knowledge) so something has to be adapted.
3. Creating a consumer similar to Aspire Postgres that understands what it was provided and spins up RavenDb intelligently in Di based on what was passed as the connection string.
4. Making sure that the metadata is setup correctly and is consumable.
5. Contributing to the Azure build process to spin up/link to RavenDb Cloud hosted in Azure automatically as part of a deploy.
6. Contributing to the same for AWS
7. Contributing to the same for Google Cloud (doesn't really exist right now)
8. Contributing to Aspir8 to generate the same for kubernetes hosted in the kubernetes cluster. (or pint to hosted RavenDb)
9. Health checks with OpenTelemetry.

I could do No. 1 on this list relatively easily, but it should be in an Aspire.Hosting.RavenDb package that is maintained by you.  No. 2/3 is more complex but doable in that it needs to break out the connection string provided by No 1 and then spin up and install RavenDb into the DI container using the relative pathing and Service Discovery.  It's viable for me to do this, but again this should be in Aspire.HibernatingRhinos.RavenDb nuget.

No 4-9 I don't have the experience necessary to make any of that happen.

I'm happy to contribute code for any of the things that I can do if given direction.  The hardest part of No 1 and 2 I think is going to be figuring out how to setup certificates and how that links to the DI install etc. from a constructed connection string and what a connection string should look like for RavenDb. It can't be hard coded, so we have to give a mechanism that is entirely contained in the crafted connection string that can be used blindly to do DI with everything needed for success.

**Comment by ayende** [comment]
We would be happy to take over and manage any such package.
About the cloud versions, we have public API for this here: https://ravendb.net/articles/ravendb-cloud-api-and-other-updates
https://api.cloud.ravendb.net/swagger/index.html

OpenTelemtry is something we are working on right now

**Comment by JohnGalt1717** [comment]
Working on it...

**Comment by ayende** [comment]
Hi @JohnGalt1717 - I wanted to know if you made any progress here

**Comment by JohnGalt1717** [comment]
[Aspire.Hosting.RavenDb.zip](https://github.com/user-attachments/files/16922383/Aspire.Hosting.RavenDb.zip)

Here's where I have gotten.  

Some notes:

1. This is largely a lift of the Postgres implementation.
2. It introduces a connection string concept to RavenDb because it's design of Aspire. Personally I think this is a good thing everywhere given how appsettings.config works but...
3. It doesn't work yet.  It spins up the container but has issues with persistence and mounts etc.

Here's an example of how it's intended:

var ravendb = builder
    .AddRavenDb(ResourceConstants.RAVEN_DB_SERVER)
    .WithDataVolume()
    .AllowUnsecureMode()
    .AddDatabase("RavenDb", "DatabaseName");


I also have extensions that I'm working on for WithClientCertificate() and WithServerCertificate()  The intent right now with these is for them to just be paths to the actual certs but Aspire really doesn't like passing paths in. (partially tested)

Also has "WithConfiguration" which allows passing a configuration.json. (not tested)

Would also really like to make it so that the WithDataVolume could work like WithDataBindMount and allow you to specify the location of where the data is stored but... see above about passing paths in.

I think it's a few hours of debugging on my part from working, but I haven't had time recently. Hopefully it's of some use to you.

(also it automatically handles the :latest doesn't support multi-targeting for intel and arm issue with the RavenDb docker containers.)

**Comment by ayende** [comment]
Thanks, we'll take a deeper look

**Comment by JohnGalt1717** [comment]
Here's a quick and dirty version using the container functionality if anyone is interested:

public static class RavenDbAspireExtensions
{
    public static IResourceBuilder<ContainerResource> ConfigureRavenDb(
        this IDistributedApplicationBuilder builder,
        string dataDir
    )
    {
        var ravendb = builder
            .AddContainer(ResourceConstants.RAVEN_DB_SERVER, "ravendb/ravendb", "latest")
            .WithBindMount(
                Path.Combine(dataDir, "ravendb", "config.json"),
                "/usr/lib/ravendb/server/settings.json"
            )
            .WithBindMount(
                Path.Combine(dataDir, "ravendb", "license.json"),
                "/usr/lib/ravendb/server/license.json"
            )
            .WithBindMount(Path.Combine(dataDir, "ravendb", "data"), "/var/lib/ravendb/data")
            .WithBindMount(Path.Combine(dataDir, "ravendb", "logs"), "/var/log/ravendb/logs")
            .WithBindMount(Path.Combine(dataDir, "certificates", "ravendb"), "/certificates")
            .WithEndpoint(38889, 38888, name: "ravendataport", scheme: "tcp")
            .WithEndpoint(9081, 8080, name: "ravenwebport", scheme: "http")
            .WithEnvironment("RAVEN_Logs_Mode", "Information")
            .WithEnvironment("RAVEN_Security_UnsecuredAccessAllowed", "PublicNetwork")
            .WithEnvironment("RAVEN_Setup_Mode", "None")
            .WithEnvironment("RAVEN_License_Eula_Accepted", "True")
            .WithEnvironment("RAVEN_ServerUrl", "http://0.0.0.0:8080")
            .WithEnvironment("RAVEN_PublicServerUrl", "http://localhost:9081")
            .WithEnvironment("RAVEN_License_Path", "/usr/lib/ravendb/server/license.json");

        return ravendb;
    }
}

That being said, I think that my license.json and settings.json pathing is wrong, but I can't seem to get it right based on the docs within docker. (It would be nice to have a call out in the docs for what the exact paths are in docker for these files for mounting in general.)

**Comment by kamranayub** [comment]
@JohnGalt1717 here is what I have mounted and configured for my local RavenDB docker compose. This is using Windows Containers:

```yml
services:

  db:
    image: ravendb/ravendb:6.0-windows-ltsc2022-latest
    hostname: a.mycompany.ravendb.community
    container_name: myapp-db
    ports:
      - "8080:8080"
      - "38888:38888"
    environment:
      - "RAVEN_PublicServerUrl=https://a.mycompany.ravendb.community:8080"
      - "RAVEN_PublicServerUrl_Tcp=tcp://a.mycompany.ravendb.community:38888"
      - "RAVEN_Setup_Mode=None"
      - "RAVEN_License_Eula_Accepted=true"
      - "RAVEN_Security_Certificate_LetsEncrypt_Email=myemail"
      - "RAVEN_Security_Certificate_Path=C:\\RavenDB\\Config\\cluster.server.certificate.mycompany.pfx"
      - "RAVEN_ServerUrl=https://0.0.0.0:8080"
      - "RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:38888"
      - "RAVEN_ARGS=--ServerUrl=https://0.0.0.0:8080 --Setup.Mode=None"
    volumes:
      - E:\RavenDB\Server\RavenData:C:\RavenDB\Server\RavenData
      - E:\RavenDB\Server\Config:C:\RavenDB\Config
 ```
 
 So the big things are:
 
 - Local folder for RavenData mapped to `C:\RavenDB\Server\RavenData` on the container
 - Local folder Config mapped to `C:\RavenDB\Config`
 - Cluster cert is _in_ the local `Config` directory so it is made available to container
 - Lets Encrypt setup
 
 For production deployment I use Ubuntu, so volume mounts are:
 
 ```
- /var/db:/var/lib/ravendb/data
- /var/db_etc:/etc/ravendb
```

The `/etc/ravendb` is the important piece -- that is where the cluster cert is read from and `settings.json` in my configuration from the container host `/var/db_etc` folder.

Hope that helps with the Docker config.

I am not using Aspire yet but I probably will migrate to it next after I'm off .NET Framework so would definitely be looking for this capability.
