### ISSUE TITLE
Can you run RavenDB with Encryption at Rest in Kubernetes?

### ISSUE THREAD

**Issue by tzarger** [ravendb/ravendb#20093]
I am trying to run RavenDB in Kubernetes, and regular database works fine. Encrypted at Rest is giving this error:

```
Raven.Client.Exceptions.Database.DatabaseLoadFailureException: Failed to start database TestEncryption
At /data/RavenData/Databases/TestEncryption
 ---> System.InsufficientMemoryException: Unable to lock memory for /data/RavenData/Databases/TestEncryption/Temp/compression.0000000000.buffers with size 16 MBytes), with encrypted databases we lock some memory in order to avoid leaking secrets to disk. Treating this as a catastrophic error and aborting the current operation.
The admin may configure higher limits using: 'sudo prlimit --pid 10 --memlock=16777216' to increase the limit. (It's recommended to do that as part of the startup script)
This behavior is controlled by the 'Security.DoNotConsiderMemoryLockFailureAsCatastrophicError' setting (expert only, modifications of this setting is not recommended).
```

Not having any luck with setting `sudo prlimit --pid 10 --memlock=16777216` in the StatefulSet Container or InitContainer since it needs a PID.

Am I missing something or just not possible?

Thanks!

**Comment by ayende** [comment]
The issue is about security and the settings inside the container.


Modify `/etc/docker/daemon.json` to include 
```
{
  "default-ulimit": {
    "memlock": {
      "Hard": -1,
      "Soft": -1
    }
  }
}
```

That would give you the same effect.

Alternatively, if you don't care about memory locking, you can set: ` 'Security.DoNotConsiderMemoryLockFailureAsCatastrophicError` to `true`.

The impact of that means that if there is swapping happening, it may spill unencrypted information to disk.

Whatever this is acceptable depends on your actual scenario.

Alternatively, can use:

```
apiVersion: v1
kind: Pod
metadata:
  name: memlock-example
spec:
  initContainers:
  - name: set-memlock
    image: busybox
    command: ["sh", "-c", "ulimit -l unlimited"]
    securityContext:
      privileged: true  
  containers:
  - name: ravendb
    image: ravendb-image
```

To enable that

**Comment by tzarger** [comment]
I have tried and here is the exact `initContainers` and still receive the same error.

```
      initContainers:
        - name: set-memlock
          image: busybox
          command: ["sh", "-c", "ulimit -l unlimited"]
          securityContext:
            privileged: true  
          volumeMounts:
            - name: data
              mountPath: /data
```

Yes, if I use `Security.DoNotConsiderMemoryLockFailureAsCatastrophicError` then it works, but were are trying to get SOC2 certification and I assume leaking unencrypted data when swapping would be a problem.
